//
//  IntersectTests.swift
//  SwiftyGeographicLib
//
//  Created by David Hart on 8/3/2026.
//

import Testing
import Numerics
@testable import Intersect
import Geodesic

// Reference values generated by a C++ program linked against GeographicLib 2.7
// using `#define private public` to access Intersect internals.

@Test func testConstructorConstants() {
    let inter = Intersect(geodesic: .wgs84)

    #expect(inter.a == 6378137.0)
    #expect(inter.f == 1.0 / 298.257223563)

    // authalic radius
    #expect(inter.rR.isApproximatelyEqual(to: 6371007.1809184738, relativeTolerance: 1e-12))

    // d = pi * rR
    #expect(inter.d.isApproximatelyEqual(to: 20015109.355541296, relativeTolerance: 1e-12))

    // eps, tol, delta — exact formulas
    #expect(inter.eps == 3 * Double.ulpOfOne)
    #expect(inter.tol.isApproximatelyEqual(to: 3.6407271828541154e-05, relativeTolerance: 1e-10))
    #expect(inter.delta.isApproximatelyEqual(to: 14813.101968120698, relativeTolerance: 1e-10))

    // t1–t5 and d1–d3
    #expect(inter.t1.isApproximatelyEqual(to: 19970326.371122573, relativeTolerance: 1e-9))
    #expect(inter.t2.isApproximatelyEqual(to: 20071056.447180964, relativeTolerance: 1e-9))
    #expect(inter.t3.isApproximatelyEqual(to: 20020723.578508016, relativeTolerance: 1e-9))
    #expect(inter.t4.isApproximatelyEqual(to: 19970326.371122573, relativeTolerance: 1e-9))
    #expect(inter.t5.isApproximatelyEqual(to: 20003931.458625447, relativeTolerance: 1e-9))
    #expect(inter.d1.isApproximatelyEqual(to: 10035528.223590482, relativeTolerance: 1e-9))
    #expect(inter.d2.isApproximatelyEqual(to: 13347149.052338677, relativeTolerance: 1e-9))
    #expect(inter.d3.isApproximatelyEqual(to: 19955513.269154452, relativeTolerance: 1e-9))
}

@Test func testEllipsoidArea() {
    let geod = Geodesic.wgs84
    #expect(geod.ellipsoidArea.isApproximatelyEqual(to: 510065621724088.44, relativeTolerance: 1e-12))
}

// Reference values from IntersectTool (GeographicLib 2.7):
//   echo "0 0 45 1 2 135" | IntersectTool -c -p 17
//   => 235587.31869382600416429 -79191.64043588734057266 0
//   echo "40 -75 30 45 -80 310" | IntersectTool -c -p 17
//   => 144727.45943665524828248 -642534.08692900557070971 0

@Test func testClosest() {
    let inter = Intersect(geodesic: .wgs84)

    let p1 = inter.closest(
        latitudeX: 0, longitudeX: 0, azimuthX: 45,
        latitudeY: 1, longitudeY: 2, azimuthY: 135)
    #expect(p1.x.isApproximatelyEqual(to: 235587.31869382600, absoluteTolerance: 0.01))
    #expect(p1.y.isApproximatelyEqual(to: -79191.64043588734, absoluteTolerance: 0.01))
    #expect(p1.c == 0)

    let p2 = inter.closest(
        latitudeX: 40, longitudeX: -75, azimuthX: 30,
        latitudeY: 45, longitudeY: -80, azimuthY: 310)
    #expect(p2.x.isApproximatelyEqual(to: 144727.45943665525, absoluteTolerance: 0.01))
    #expect(p2.y.isApproximatelyEqual(to: -642534.08692900557, absoluteTolerance: 0.01))
    #expect(p2.c == 0)
}

// Reference:
//   echo "0 0 45 135" | IntersectTool -n -p 17
//   => -19987139.50000064820051193 -19987139.50000064820051193 0

@Test func testNext() {
    let inter = Intersect(geodesic: .wgs84)

    let p = inter.next(
        latitude: 0, longitude: 0,
        azimuthX: 45, azimuthY: 135)
    #expect(p.x.isApproximatelyEqual(to: -19987139.5000006, absoluteTolerance: 0.1))
    #expect(p.y.isApproximatelyEqual(to: -19987139.5000006, absoluteTolerance: 0.1))
    #expect(p.c == 0)
}

// Reference values from IntersectTool (GeographicLib 2.7):
//   echo "0 -1 0 1 -1 0 1 0" | IntersectTool -i -p 17
//   => 111319.49079327355138958 110574.38855779878213070 0 0
//   echo "40 -75 50 -70 35 -80 45 -60" | IntersectTool -i -p 17
//   => -286064.12203504319768399 457605.29710917058400810 0 -3

@Test func testSegment() {
    let inter = Intersect(geodesic: .wgs84)

    // Segments that actually cross (segmentMode = 0)
    let r1 = inter.segment(
        latitudeX1: 0, longitudeX1: -1,
        latitudeX2: 0, longitudeX2: 1,
        latitudeY1: -1, longitudeY1: 0,
        latitudeY2: 1, longitudeY2: 0)
    #expect(r1.point.x.isApproximatelyEqual(to: 111319.49079327355, absoluteTolerance: 0.01))
    #expect(r1.point.y.isApproximatelyEqual(to: 110574.38855779878, absoluteTolerance: 0.01))
    #expect(r1.point.c == 0)
    #expect(r1.segmentMode == 0)

    // Segments that don't cross (segmentMode = -3)
    let r2 = inter.segment(
        latitudeX1: 40, longitudeX1: -75,
        latitudeX2: 50, longitudeX2: -70,
        latitudeY1: 35, longitudeY1: -80,
        latitudeY2: 45, longitudeY2: -60)
    #expect(r2.point.x.isApproximatelyEqual(to: -286064.12203504320, absoluteTolerance: 0.01))
    #expect(r2.point.y.isApproximatelyEqual(to: 457605.29710917058, absoluteTolerance: 0.01))
    #expect(r2.point.c == 0)
    #expect(r2.segmentMode == -3)
}

// Reference:
//   echo "0 0 45 1 2 135" | IntersectTool -R 1000000 -p 17
//   => 235587.31869382600416429 -79191.64043588734057266 0 314778.95912971335928887

@Test func testAll() {
    let inter = Intersect(geodesic: .wgs84)

    let pts = inter.all(
        latitudeX: 0, longitudeX: 0, azimuthX: 45,
        latitudeY: 1, longitudeY: 2, azimuthY: 135,
        maxDistance: 1_000_000)
    #expect(pts.count == 1)
    #expect(pts[0].x.isApproximatelyEqual(to: 235587.31869382600, absoluteTolerance: 0.01))
    #expect(pts[0].y.isApproximatelyEqual(to: -79191.64043588734, absoluteTolerance: 0.01))
    #expect(pts[0].c == 0)
}

#if canImport(CoreLocation)
import CoreLocation

// Verify closestIntersection returns a CLLocationCoordinate2D consistent with
// the displacement-based closest() result.
@Test func testClosestIntersectionCoordinate() {
    let geod = Geodesic.wgs84
    let inter = Intersect(geodesic: geod)

    let lineX = geod.line(latitude: 0, longitude: 0, azimuth: 45)
    let lineY = geod.line(latitude: 1, longitude: 2, azimuth: 135)

    let result = inter.closestIntersection(lineX: lineX, lineY: lineY)

    guard case .point(let coord) = result else {
        Issue.record("Expected .point, got \(result)")
        return
    }

    // Cross-check: evaluate lineX at the displacement from closest()
    let p = inter.closest(lineX: lineX, lineY: lineY)
    let pos = lineX.position(distance: p.x)
    #expect(coord.latitude.isApproximatelyEqual(to: pos.latitude, absoluteTolerance: 1e-12))
    #expect(coord.longitude.isApproximatelyEqual(to: pos.longitude, absoluteTolerance: 1e-12))
}

// Reference:
//   echo "0 0 0 1 0 0" | IntersectTool -c -p 17
//   => 55287.19427889938378939 -55287.19427889938378939 1
@Test func testClosestIntersectionParallel() {
    let geod = Geodesic.wgs84
    let inter = Intersect(geodesic: geod)

    // Two lines on the same meridian, both heading north
    let lineX = geod.line(latitude: 0, longitude: 0, azimuth: 0)
    let lineY = geod.line(latitude: 1, longitude: 0, azimuth: 0)

    let result = inter.closestIntersection(lineX: lineX, lineY: lineY)

    guard case .parallel = result else {
        Issue.record("Expected .parallel, got \(result)")
        return
    }

    // Verify the underlying Point has c == 1
    let p = inter.closest(lineX: lineX, lineY: lineY)
    #expect(p.c == 1)
}

// Reference:
//   echo "0 0 0 1 0 180" | IntersectTool -c -p 17
//   => 55287.19427889938378939 55287.19427889938378939 -1
@Test func testClosestIntersectionAntiParallel() {
    let geod = Geodesic.wgs84
    let inter = Intersect(geodesic: geod)

    // Two lines on the same meridian, opposite directions
    let lineX = geod.line(latitude: 0, longitude: 0, azimuth: 0)
    let lineY = geod.line(latitude: 1, longitude: 0, azimuth: 180)

    let result = inter.closestIntersection(lineX: lineX, lineY: lineY)

    guard case .antiParallel = result else {
        Issue.record("Expected .antiParallel, got \(result)")
        return
    }

    // Verify the underlying Point has c == -1
    let p = inter.closest(lineX: lineX, lineY: lineY)
    #expect(p.c == -1)
}
#endif
