//
//  IntersectTests.swift
//  SwiftyGeographicLib
//
//  Created by David Hart on 8/3/2026.
//

import Testing
@testable import Intersect
import Geodesic

// Reference values generated by a C++ program linked against GeographicLib 2.7
// using `#define private public` to access Intersect internals.

@Test func testConstructorConstants() {
    let inter = Intersect(geodesic: .wgs84)

    #expect(inter.a == 6378137.0)
    #expect(inter.f == 1.0 / 298.257223563)

    // authalic radius
    let rRRef = 6371007.1809184738
    #expect(abs(inter.rR - rRRef) < 1e-6)

    // d = pi * rR
    let dRef = 20015109.355541296
    #expect(abs(inter.d - dRef) < 1e-4)

    // eps, tol, delta — exact formulas
    #expect(inter.eps == 3 * Double.ulpOfOne)
    let tolRef = 3.6407271828541154e-05
    #expect(abs(inter.tol - tolRef) / tolRef < 1e-10)
    let deltaRef = 14813.101968120698
    #expect(abs(inter.delta - deltaRef) / deltaRef < 1e-10)

    // t1–t5 and d1–d3
    let t1Ref = 19970326.371122573
    let t2Ref = 20071056.447180964
    let t3Ref = 20020723.578508016
    let t4Ref = 19970326.371122573
    let t5Ref = 20003931.458625447
    let d1Ref = 10035528.223590482
    let d2Ref = 13347149.052338677
    let d3Ref = 19955513.269154452

    #expect(abs(inter.t1 - t1Ref) / t1Ref < 1e-9)
    #expect(abs(inter.t2 - t2Ref) / t2Ref < 1e-9)
    #expect(abs(inter.t3 - t3Ref) / t3Ref < 1e-9)
    #expect(abs(inter.t4 - t4Ref) / t4Ref < 1e-9)
    #expect(abs(inter.t5 - t5Ref) / t5Ref < 1e-9)
    #expect(abs(inter.d1 - d1Ref) / d1Ref < 1e-9)
    #expect(abs(inter.d2 - d2Ref) / d2Ref < 1e-9)
    #expect(abs(inter.d3 - d3Ref) / d3Ref < 1e-9)
}

@Test func testEllipsoidArea() {
    let geod = Geodesic.wgs84
    let areaRef = 510065621724088.44
    #expect(abs(geod.ellipsoidArea - areaRef) / areaRef < 1e-12)
}

// Reference values from IntersectTool (GeographicLib 2.7):
//   echo "0 0 45 1 2 135" | IntersectTool -c -p 17
//   => 235587.31869382600416429 -79191.64043588734057266 0
//   echo "40 -75 30 45 -80 310" | IntersectTool -c -p 17
//   => 144727.45943665524828248 -642534.08692900557070971 0

@Test func testClosest() {
    let inter = Intersect(geodesic: .wgs84)

    let p1 = inter.closest(
        latitudeX: 0, longitudeX: 0, azimuthX: 45,
        latitudeY: 1, longitudeY: 2, azimuthY: 135)
    #expect(abs(p1.x - 235587.31869382600) < 0.01)
    #expect(abs(p1.y - (-79191.64043588734)) < 0.01)
    #expect(p1.c == 0)

    let p2 = inter.closest(
        latitudeX: 40, longitudeX: -75, azimuthX: 30,
        latitudeY: 45, longitudeY: -80, azimuthY: 310)
    #expect(abs(p2.x - 144727.45943665525) < 0.01)
    #expect(abs(p2.y - (-642534.08692900557)) < 0.01)
    #expect(p2.c == 0)
}

// Reference:
//   echo "0 0 45 135" | IntersectTool -n -p 17
//   => -19987139.50000064820051193 -19987139.50000064820051193 0

@Test func testNext() {
    let inter = Intersect(geodesic: .wgs84)

    let p = inter.next(
        latitude: 0, longitude: 0,
        azimuthX: 45, azimuthY: 135)
    #expect(abs(p.x - (-19987139.5000006)) < 0.1)
    #expect(abs(p.y - (-19987139.5000006)) < 0.1)
    #expect(p.c == 0)
}

// Reference values from IntersectTool (GeographicLib 2.7):
//   echo "0 -1 0 1 -1 0 1 0" | IntersectTool -i -p 17
//   => 111319.49079327355138958 110574.38855779878213070 0 0
//   echo "40 -75 50 -70 35 -80 45 -60" | IntersectTool -i -p 17
//   => -286064.12203504319768399 457605.29710917058400810 0 -3

@Test func testSegment() {
    let inter = Intersect(geodesic: .wgs84)

    // Segments that actually cross (segmentMode = 0)
    let r1 = inter.segment(
        latitudeX1: 0, longitudeX1: -1,
        latitudeX2: 0, longitudeX2: 1,
        latitudeY1: -1, longitudeY1: 0,
        latitudeY2: 1, longitudeY2: 0)
    #expect(abs(r1.point.x - 111319.49079327355) < 0.01)
    #expect(abs(r1.point.y - 110574.38855779878) < 0.01)
    #expect(r1.point.c == 0)
    #expect(r1.segmentMode == 0)

    // Segments that don't cross (segmentMode = -3)
    let r2 = inter.segment(
        latitudeX1: 40, longitudeX1: -75,
        latitudeX2: 50, longitudeX2: -70,
        latitudeY1: 35, longitudeY1: -80,
        latitudeY2: 45, longitudeY2: -60)
    #expect(abs(r2.point.x - (-286064.12203504320)) < 0.01)
    #expect(abs(r2.point.y - 457605.29710917058) < 0.01)
    #expect(r2.point.c == 0)
    #expect(r2.segmentMode == -3)
}

// Reference:
//   echo "0 0 45 1 2 135" | IntersectTool -R 1000000 -p 17
//   => 235587.31869382600416429 -79191.64043588734057266 0 314778.95912971335928887

@Test func testAll() {
    let inter = Intersect(geodesic: .wgs84)

    let pts = inter.all(
        latitudeX: 0, longitudeX: 0, azimuthX: 45,
        latitudeY: 1, longitudeY: 2, azimuthY: 135,
        maxDistance: 1_000_000)
    #expect(pts.count == 1)
    #expect(abs(pts[0].x - 235587.31869382600) < 0.01)
    #expect(abs(pts[0].y - (-79191.64043588734)) < 0.01)
    #expect(pts[0].c == 0)
}
